import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{motion,AnimatePresence}from'framer-motion';import{Sparkles,RefreshCcw,Share2}from'lucide-react';import'./style.css';
const stats=['execution','collab','experiment','detail','data','emotion','trend','strategy'];
const labels={execution:'실행력',collab:'협업력',experiment:'실험성',detail:'디테일',data:'데이터 감각',emotion:'감성력',trend:'트렌드 감지력',strategy:'전략력'};
const hidden={deadline:'마감 생존력',overtime:'야근 적응도',meeting:'회의 발언 확률',revision:'수정 요청 내성',urgent:'급한 일정 대응력',folder:'파일 정리 확률'};
const types={
launcher:{name:'번개 런처',tag:'일단 공개하고 개선하는 스피드형',color:'#7dd3fc',quote:'일단 올리고 반응 보죠!',match:'디테일 장인',mismatch:'감성 큐레이터',strength:['빠른 실행과 배포','트렌드 대응 속도','마감 직전 돌파력'],weak:['검수 누락 가능','브랜드 톤보다 속도 우선','긴 논의에 쉽게 지침'],style:['회의 끝나자마자 초안 생성','완벽보다 런칭을 선호','수정은 공개 후에도 가능하다고 믿음'],base:{execution:96,collab:64,experiment:78,detail:46,data:58,emotion:48,trend:82,strategy:55,deadline:92,overtime:71,meeting:63,revision:54,urgent:94,folder:31}},
hunter:{name:'알고리즘 헌터',tag:'숫자와 반응을 추적하는 최적화형',color:'#a78bfa',quote:'근데 이거 CTR은 얼마예요?',match:'실험 탐험가',mismatch:'감성 큐레이터',strength:['수치 기반 판단','성과 개선 루프','A/B 테스트 감각'],weak:['감성적 설득에 약함','초기 아이디어가 차갑게 보일 수 있음','브랜드 무드를 숫자로 환산하려 함'],style:['대시보드 먼저 켬','썸네일도 지표로 판단','가설-실험-개선 루프를 좋아함'],base:{execution:70,collab:55,experiment:84,detail:67,data:98,emotion:36,trend:74,strategy:79,deadline:68,overtime:66,meeting:49,revision:72,urgent:71,folder:62}},
curator:{name:'감성 큐레이터',tag:'브랜드의 무드와 세계관을 지키는 감각형',color:'#f9a8d4',quote:'지금 톤이 조금 안 맞는 것 같아요.',match:'전략 설계자',mismatch:'번개 런처',strength:['브랜드 무드 설계','팬덤형 콘텐츠 감각','결과물 완성도'],weak:['속도전에서 스트레스','수치만으로 평가받기 싫어함','마지막 수정이 길어짐'],style:['레퍼런스 저장 장인','색감과 문장 톤에 민감','작은 어긋남을 잘 발견함'],base:{execution:54,collab:78,experiment:59,detail:88,data:42,emotion:98,trend:76,strategy:65,deadline:49,overtime:73,meeting:67,revision:81,urgent:45,folder:84}},
artisan:{name:'디테일 장인',tag:'검수와 완성도를 책임지는 퀄리티 보스',color:'#fcd34d',quote:'잠깐만요, 자막 싱크 한 프레임 밀렸어요.',match:'번개 런처',mismatch:'트렌드 레이더',strength:['오류 발견력','퀄리티 관리','안정적인 산출물'],weak:['완료 버튼을 늦게 누름','변수가 많은 상황에 피로','가끔 전체보다 부분에 몰입'],style:['체크리스트를 사랑함','최종_final_진짜최종 파일 생성','업로드 전 3번 더 봄'],base:{execution:57,collab:70,experiment:45,detail:99,data:64,emotion:68,trend:44,strategy:62,deadline:61,overtime:80,meeting:52,revision:89,urgent:55,folder:96}},
explorer:{name:'실험 탐험가',tag:'새 포맷과 낯선 시도를 즐기는 개척형',color:'#86efac',quote:'이거 릴스로 한번 비틀어보면 어때요?',match:'알고리즘 헌터',mismatch:'디테일 장인',strength:['새로운 포맷 발굴','실험 설계','분위기 전환'],weak:['반복 운영에 쉽게 지루함','완성도 관리가 흔들릴 수 있음','아이디어가 너무 많음'],style:['처음 보는 기능은 눌러봄','레퍼런스를 이상한 곳에서 찾음','기획서에 실험안이 늘어남'],base:{execution:73,collab:62,experiment:99,detail:43,data:71,emotion:69,trend:86,strategy:68,deadline:74,overtime:59,meeting:58,revision:48,urgent:76,folder:37}},
coordinator:{name:'밸런스 코디네이터',tag:'사람과 일정을 부드럽게 연결하는 협업형',color:'#93c5fd',quote:'좋아요, 그럼 역할을 이렇게 나눠볼게요.',match:'트렌드 레이더',mismatch:'알고리즘 헌터',strength:['협업 조율','갈등 완충','일정 관리'],weak:['자기 일보다 조율에 에너지 소모','강한 주장 앞에서 피곤함','결정 지연 가능'],style:['회의록을 예쁘게 정리','중간에서 맥락 번역','팀 분위기를 먼저 봄'],base:{execution:66,collab:98,experiment:52,detail:76,data:58,emotion:80,trend:56,strategy:74,deadline:72,overtime:64,meeting:88,revision:75,urgent:69,folder:82}},
radar:{name:'트렌드 레이더',tag:'밈과 이슈를 누구보다 빨리 감지하는 감지형',color:'#fb7185',quote:'이거 지금 타이밍에 올리면 먹힐 것 같아요.',match:'밸런스 코디네이터',mismatch:'디테일 장인',strength:['트렌드 캐치','소셜 감각','타이밍 판단'],weak:['롱텀 전략이 약할 수 있음','검수보다 순간감 우선','유행 지나면 흥미 감소'],style:['출근 전부터 피드 체크','밈을 업무 언어로 번역','이슈 타이밍에 민감'],base:{execution:81,collab:67,experiment:79,detail:39,data:61,emotion:74,trend:99,strategy:47,deadline:82,overtime:57,meeting:65,revision:43,urgent:87,folder:29}},
strategist:{name:'전략 설계자',tag:'큰 그림과 방향성을 설계하는 기획형',color:'#c4b5fd',quote:'이 콘텐츠가 결국 어떤 포지션을 만들까요?',match:'감성 큐레이터',mismatch:'번개 런처',strength:['구조화와 방향 설정','장기 캠페인 설계','맥락 파악'],weak:['실행 속도가 느려 보일 수 있음','작은 작업에 답답함','즉흥 대응에 약함'],style:['왜 하는지부터 확인','기획서 목차를 먼저 잡음','성과보다 포지션을 함께 봄'],base:{execution:58,collab:73,experiment:65,detail:72,data:76,emotion:62,trend:55,strategy:99,deadline:57,overtime:62,meeting:74,revision:70,urgent:52,folder:78}}
};
const questions=[
{q:'마감 3시간 전, 가장 먼저 하는 행동은?',o:[['최소 완성본부터 올린다','launcher'],['오탈자와 싱크를 다시 본다','artisan'],['성과 가능성을 다시 계산한다','hunter'],['톤앤매너를 끝까지 맞춘다','curator']]},
{q:'새로운 플랫폼 기능이 생겼다.',o:[['바로 테스트 콘텐츠를 만든다','explorer'],['유행 타이밍을 살핀다','radar'],['팀 역할을 나눠본다','coordinator'],['전체 전략과 맞는지 본다','strategist']]},
{q:'내 업무 스타일에 가까운 말은?',o:[['빠르게 던지고 반응을 본다','launcher'],['숫자가 답을 말해준다','hunter'],['느낌이 맞아야 오래 간다','curator'],['실수 없는 게 제일 중요하다','artisan']]},
{q:'회의에서 나는 보통?',o:[['액션 아이템을 정리한다','coordinator'],['새 아이디어를 던진다','explorer'],['근거 데이터를 묻는다','hunter'],['방향성을 정리한다','strategist']]},
{q:'가장 신경 쓰이는 콘텐츠 요소는?',o:[['업로드 타이밍','radar'],['완성도와 검수','artisan'],['브랜드 무드','curator'],['실험 가능성','explorer']]},
{q:'갑작스러운 수정 요청이 들어오면?',o:[['바로 고친다','launcher'],['영향 범위를 먼저 본다','strategist'],['팀과 우선순위를 조율한다','coordinator'],['수정 후 재검수까지 한다','artisan']]},
{q:'가장 즐거운 순간은?',o:[['지표가 오른 걸 확인할 때','hunter'],['새 포맷이 먹혔을 때','explorer'],['팀이 착착 맞을 때','coordinator'],['밈 타이밍을 잡았을 때','radar']]},
{q:'업무 결과물에서 칭찬받고 싶은 건?',o:[['빠른 실행','launcher'],['정확한 분석','hunter'],['감각적인 완성도','curator'],['큰 그림이 좋은 기획','strategist']]}
];
function Character({type}){let t=types[type];return <svg viewBox="0 0 300 300" className="char"><defs><linearGradient id={'g'+type} x1="0" x2="1"><stop stopColor={t.color}/><stop offset="1" stopColor="#fff"/></linearGradient></defs><circle cx="150" cy="150" r="118" fill={`url(#g${type})`} opacity=".9"/><ellipse cx="150" cy="242" rx="72" ry="18" fill="#000" opacity=".14"/><rect x="96" y="88" width="108" height="118" rx="42" fill="#fff7ed" stroke="#1f2937" strokeWidth="7"/><circle cx="128" cy="140" r="8" fill="#111827"/><circle cx="174" cy="140" r="8" fill="#111827"/><path d="M132 169 Q150 184 170 169" fill="none" stroke="#111827" strokeWidth="6" strokeLinecap="round"/><path d="M100 106 Q145 42 201 105" fill="#111827"/>{type==='hunter'&&<><path d="M205 102 l38-18" stroke="#111827" strokeWidth="7"/><rect x="210" y="70" width="48" height="30" rx="8" fill="#fff" stroke="#111827" strokeWidth="5"/><path d="M222 89 h24" stroke={t.color} strokeWidth="5"/></>}{type==='curator'&&<><circle cx="219" cy="108" r="19" fill="#fff" stroke="#111827" strokeWidth="5"/><path d="M211 107 h16 M219 99 v16" stroke={t.color} strokeWidth="5"/></>}{type==='launcher'&&<><path d="M209 175 l45 24 l-39 13" fill="#fff" stroke="#111827" strokeWidth="6"/><path d="M214 191 h22" stroke={t.color} strokeWidth="5"/></>}{type==='artisan'&&<><rect x="207" y="165" width="44" height="30" rx="8" fill="#fff" stroke="#111827" strokeWidth="5"/><path d="M216 181 h26" stroke={t.color} strokeWidth="5"/></>}{type==='explorer'&&<><path d="M218 74 l22 38 l-43 0z" fill="#fff" stroke="#111827" strokeWidth="5"/><circle cx="219" cy="101" r="5" fill={t.color}/></>}{type==='coordinator'&&<><circle cx="221" cy="92" r="15" fill="#fff" stroke="#111827" strokeWidth="5"/><circle cx="250" cy="122" r="15" fill="#fff" stroke="#111827" strokeWidth="5"/><path d="M232 103 l9 9" stroke="#111827" strokeWidth="5"/></>}{type==='radar'&&<><path d="M212 90 q30 20 0 40" fill="none" stroke="#111827" strokeWidth="5"/><path d="M226 78 q47 35 0 68" fill="none" stroke="#111827" strokeWidth="5"/></>}{type==='strategist'&&<><rect x="210" y="78" width="46" height="46" rx="10" fill="#fff" stroke="#111827" strokeWidth="5"/><path d="M221 112 l24-24 M221 91 h22 v22" stroke={t.color} strokeWidth="5" fill="none"/></>}<rect x="107" y="198" width="86" height="50" rx="24" fill="#111827"/><path d="M119 218 h62" stroke={t.color} strokeWidth="7" strokeLinecap="round"/></svg>}
function App(){const[step,setStep]=useState(-1),[score,setScore]=useState({});const result=useMemo(()=>{let entries=Object.entries(score);if(!entries.length)return'launcher';return entries.sort((a,b)=>b[1]-a[1])[0][0]},[score]);const add=(type)=>{setScore(s=>({...s,[type]:(s[type]||0)+1}));setStep(v=>v+1)};const done=step>=questions.length;const res=types[result];const merged=done?res.base:null;const reset=()=>{setStep(-1);setScore({})};return <main><section className="shell"><div className="nav"><b>OCG WorkType</b><span>업무 능력치 측정기</span></div><AnimatePresence mode="wait">{step<0&&<motion.div className="hero" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0}}><div className="pill"><Sparkles size={16}/> 온라인컨텐츠그룹 업무 유형 테스트</div><h1>당신의 콘텐츠 업무 캐릭터를 분석합니다.</h1><p>귀엽지만 은근히 정확한 업무 성향 테스트. 클릭 몇 번으로 능력치, 강약점, 찰떡 궁합과 상극 타입까지 확인해요.</p><button onClick={()=>setStep(0)}>능력치 측정 시작</button><div className="presets">{Object.values(types).slice(0,4).map(t=><span key={t.name}>{t.name}</span>)}</div></motion.div>}{step>=0&&!done&&<motion.div className="card" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0}}><div className="progress"><span style={{width:`${(step/questions.length)*100}%`}}/></div><p className="scan">업무 패턴 스캔 중... {step+1}/{questions.length}</p><h2>{questions[step].q}</h2><div className="grid">{questions[step].o.map(([txt,type])=><button className="opt" key={txt} onClick={()=>add(type)}>{txt}</button>)}</div></motion.div>}{done&&<motion.div className="result" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><div className="resultTop"><div><p className="scan">측정 완료 · 캐릭터 생성됨</p><h1>{res.name}</h1><h3>{res.tag}</h3><blockquote>“{res.quote}”</blockquote></div><Character type={result}/></div><div className="panel"><h2>업무 능력치</h2>{stats.map(k=><div className="bar" key={k}><span>{labels[k]}</span><i><b style={{width:merged[k]+'%',background:res.color}}/></i><em>{merged[k]}</em></div>)}</div><div className="cols"><div className="panel"><h2>강점</h2>{res.strength.map(x=><p key={x}>✅ {x}</p>)}</div><div className="panel"><h2>약점</h2>{res.weak.map(x=><p key={x}>⚠️ {x}</p>)}</div></div><div className="panel"><h2>평소 업무 스타일</h2>{res.style.map(x=><p key={x}>· {x}</p>)}</div><div className="cols"><div className="panel"><h2>잘 맞는 타입</h2><p>🤝 {res.match}</p></div><div className="panel"><h2>살짝 안 맞는 타입</h2><p>🧊 {res.mismatch}</p></div></div><div className="panel"><h2>Hidden Stats</h2>{Object.keys(hidden).map(k=><div className="bar small" key={k}><span>{hidden[k]}</span><i><b style={{width:merged[k]+'%',background:res.color}}/></i><em>{merged[k]}%</em></div>)}</div><div className="actions"><button onClick={reset}><RefreshCcw size={16}/> 다시 하기</button><button onClick={()=>navigator.clipboard?.writeText(location.href)}><Share2 size={16}/> 링크 복사</button></div></motion.div>}</AnimatePresence></section></main>}
createRoot(document.getElementById('root')).render(<App/>);
